language: scala
jdk:
   - oraclejdk7
   - oraclejdk8
scala:
   - 2.10.6
   - 2.11.8
   - 2.12.6
   - 2.13.0-M4
matrix:
  exclude:
    - jdk: oraclejdk7
      scala: 2.12.6
    - jdk: oraclejdk7
      scala: 2.13.0-M4
